Cleaned up unneeded directories. Code generation now uses environment variables.
All M4 files used during code generation were moved into the M4/m4 directory to
provide a single location for M4 libraries.

The code generation scripts and makefile now make use of the new environment
variables set by the profile.d script to perform library detection and other
tasks.

Note: With this revision, the only real way to run DataPath is through the
driver script, which can be installed by running  `make install` after
compiling DataPath.

diff --git a/tools/datapath b/tools/datapath
--- a/tools/datapath
+++ b/tools/datapath
@@ -19,8 +19,10 @@
 # This script will be linked into /usr/local/bin during installation so that
 # datapath can be run from any directory in the system.
 
+##### Helper Functions #####
+
 function printUsage {
-    echo "Usage: datapath [options] <command> <file>"
+    echo "Usage: datapath [options] <command> [file]"
     echo "Supported commands are:"
     echo "      run"
     echo "      debug"
@@ -32,6 +34,168 @@ function printUsage {
     echo "  -w              Disable read-only mode"
     echo "  -v              Enable verbose ouput"
 }
+
+function getFile {
+    FILE=$(readlink -e $1)
+
+    if [ $? != 0 ]; then
+        echo "Error: File $1 not found."
+        exit -1
+    fi
+}
+
+# Returns 1 if yes and 0 if no
+# $1 = Prompt
+function getYesOrNo {
+    # Valid answers for yes and no
+    local ANS_YES="y yes"
+    local ANS_NO="n no"
+
+    while [ 0 ]; do
+        read -p "$1" ans
+
+        # Check if yes
+        echo $ANS_YES | grep -i -w "$ans" &>/dev/null
+        if [ $? == 0 ]; then
+            return 1
+        fi
+
+        # Check if no
+        echo $ANS_NO | grep -i -w "$ans" &>/dev/null
+        if [ $? == 0 ]; then
+            return 0
+        fi
+
+        # Didn't get either
+        echo "Please answer y(es) or n(o)."
+    done
+}
+
+function runTest {
+    cd $DP_DIR
+
+    if [ $NO_OPTS == true ]; then
+        # Turn off optimizations
+        export DEBUG_DATAPATH=true
+    fi
+
+    if [ $debug == 1 ]; then
+        # Run through the debugger
+        cat > gdb-commands <<EOF
+run $DP_OPTS $1
+EOF
+
+        gdb --command=gdb-commands ./dp
+    else
+        # Just run normally
+        ./dp $DP_OPTS $1
+    fi
+}
+
+# $1 = List of paths (colon separated)
+# $2 = subdirectory in those paths to check for
+function getExistingSubpaths {
+    local allPaths=""
+
+    local prevIFS="$IFS"
+    IFS=":"
+
+    for path in "$1"; do
+        cannonicalPath=$(readlink -e $path)
+        if [ $? == 0 ]; then
+            allPaths+="${IFS}${cannonicalPath}"
+        fi
+    done
+
+    IFS="$prevIFS"
+
+    echo "$allPaths"
+}
+
+function getPaths {
+    # Set up Datapath installation paths
+
+    if [ "x$DATAPATH_INSTALL_PATH" == "x" ]; then
+        # DATAPATH_INSTALL_PATH is not set
+        echo "Error: DataPath environment variables are not set."
+        echo "If you have recently installed DataPath, please close your current terminal and"
+        echo "start a new one. They environment variables are only set for terminals created"
+        echo "after the installation of DataPath."
+        exit -1
+    else
+        BASE_DIR=$DATAPATH_INSTALL_PATH
+    fi
+
+    DP_DIR=$DATAPATH_EXEC_PATH
+    DP_LOCK_FILE=$DATAPATH_LOCK_FILE
+
+    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:$(getExistingSubpaths "$DATAPATH_LIBRARY_PATH" "libraries")
+    export LD_LIBRARY_PATH
+
+    if [ $VERBOSE == 1 ]; then
+        echo "Install Directory     : $BASE_DIR"
+        echo "Executable Directory  : $DP_DIR"
+        echo "Library path(s)       : $DATAPATH_LIBRARY_PATH"
+        echo "Shared Libraries      : $DP_SHARED_LIB_DIR"
+        echo "Lock File             : $DP_LOCK_FILE"
+        echo "LD_LIBRARY_PATH       : $LD_LIBRARY_PATH"
+    fi
+}
+
+function executeDatapath {
+    getPaths
+
+    if [ ! -e $DP_LOCK_FILE ]; then
+        touch $DP_LOCK_FILE
+        if (($? != 0)); then
+            echo "Failed to create lock file at $DP_LOCK_FILE"
+            echo "Please contact the system administrator."
+            exit 1
+        fi
+    fi
+
+    # Open the lock file
+    exec 9<$DP_LOCK_FILE
+
+    finished=0
+    exitCode=0
+    while (( $finished == 0 )); do
+        # Try to lock the datapath-lock
+        flock -n 9
+        if (( $? != 0 )); then
+            if (($INTERACTIVE == 0)); then
+                # Just exit
+                exitCode=1
+                finished=1
+                continue
+            fi
+
+            echo "Warning: A DataPath process is currently running."
+            echo "Do you wish to terminate the currently running process?"
+
+            if [ $(getYesOrNo "Kill process? (y/n): ") == 1 ]; then
+                # Kill datapath and try to get the lock again
+                gotAns=1
+                echo "Killing currently running datapath instance."
+                killall dp
+                sleep 1
+            else
+                echo "Aborting."
+                finished=1
+                exitCode=1
+            fi
+        else
+            # We got the lock
+            finished=1
+            runTest $1
+        fi
+    done
+
+    # Close the lock file
+    exec 9>&-
+}
+
+##### Argument Parsing #####
 
 NO_OPTS=false
 READ_ONLY=true
@@ -67,40 +231,13 @@ done
 
 shift $(expr $OPTIND - 1)
 
-if (( $# != 2 )); then
-    echo "Error: expected exactly 2 arguments" >&2
+if (( $# < 1 )); then
+    echo "Error: No command specified."
     printUsage
     exit -1
 fi
 
-validCommand=1
 debug=0
-
-case $1 in
-    run)
-        ;;
-    debug)
-        debug=1
-        ;;
-    *)
-        validCommand=0
-        ;;
-esac
-
-if [ $validCommand = 0 ]; then
-    echo "Error: Unsupported command $1"
-    printUsage
-    exit -1
-fi
-
-COMMAND=$1
-
-FILE=$(readlink -e $2)
-
-if [ $? != 0 ]; then
-    echo "Error: File $2 not found."
-    exit -1
-fi
 
 DP_OPTS="-q"
 if [ $READ_ONLY == true ]; then
@@ -109,128 +246,21 @@ fi
 
 DP_OPTS="$DP_OPTS -e"
 
-function runTest {
-    cd $DP_DIR
+case $1 in
+    debug)
+        debug=1
+        ;&
+    run)
+        getFile $2
+        executeDatapath $FILE
+        ;;
+    *)
+        echo "Error: Unsupported command $1"
+        printUsage
+        exit -1
+        ;;
+esac
 
-    if [ $NO_OPTS == true ]; then
-        # Turn off optimizations
-        export DEBUG_DATAPATH=true
-    fi
-
-    if [ $debug == 1 ]; then
-        # Run through the debugger
-        cat > gdb-commands <<EOF
-run $DP_OPTS $FILE
-EOF
-
-        gdb --command=gdb-commands ./dp
-    else
-        # Just run normally
-        ./dp $DP_OPTS $FILE
-    fi
-}
-
-# Set up Datapath installation paths
-
-if [ "x$DATAPATH_INSTALL_PATH" == "x" ]; then
-    # DATAPATH_INSTALL_PATH is not set
-    # Assume we are in the trunk/tools directory
-    BASE_DIR=$(readlink -f ..)
-else
-    BASE_DIR=$DATAPATH_INSTALL_PATH
-fi
-
-if [ "x$DATAPATH_EXEC_PATH" == "x" ]; then
-    DP_DIR="$BASE_DIR/src/Tool_DataPath/executable"
-else
-    DP_DIR=$DATAPATH_EXEC_PATH
-fi
-
-if [ "x$DATAPATH_SO_PATH" == "x" ]; then
-    DP_SHARED_LIB_DIR="$BASE_DIR/Libs/libraries"
-else
-    DP_SHARED_LIB_DIR=$DATAPATH_SO_PATH
-fi
-
-if [ "x$DATAPATH_LOCK_FILE" == "x" ]; then
-    DP_LOCK_FILE="$BASE_DIR/lock"
-else
-    DP_LOCK_FILE=$DATAPATH_LOCK_FILE
-fi
-
-LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64:/usr/local/lib:$DP_SHARED_LIB_DIR
-export LD_LIBRARY_PATH
-
-if [ $VERBOSE == 1 ]; then
-    echo "Install Directory     : $BASE_DIR"
-    echo "Executable Directory  : $DP_DIR"
-    echo "Shared Libraries      : $DP_SHARED_LIB_DIR"
-    echo "Lock File             : $DP_LOCK_FILE"
-    echo "LD_LIBRARY_PATH       : $LD_LIBRARY_PATH"
-fi
-
-# Valid answers for yes and no
-ANS_YES="y yes"
-ANS_NO="n no"
-
-if [ ! -e $DP_LOCK_FILE ]; then
-    touch $DP_LOCK_FILE
-    if (($? != 0)); then
-        echo "Failed to create lock file at $DP_LOCK_FILE"
-        echo "Please contact the system administrator."
-        exit 1
-    fi
-fi
-
-# Open the lock file
-exec 9<$DP_LOCK_FILE
-
-finished=0
-exitCode=0
-while (( $finished == 0 )); do
-    # Try to lock the datapath-lock
-    flock -n 9
-    if (( $? != 0 )); then
-        if (($INTERACTIVE == 0)); then
-            # Just exit
-            exitCode=1
-            finished=1
-            continue
-        fi
-
-        echo "Warning: A DataPath process is currently running."
-        echo "Do you wish to terminate the currently running process?"
-
-        gotAns=0
-        while [ $gotAns == 0 ]; do
-            read -p "Kill process? (y/n): " ans
-            echo $ANS_YES | grep -i -w "$ans" &>/dev/null
-            if (( $? == 0 )); then
-                # Kill datapath and try to get the lock again
-                gotAns=1
-                echo "Killing currently running datapath instance."
-                killall dp
-                sleep 1
-            else
-                echo $ANS_NO | grep -i -w "$ans" &>/dev/null
-                if (( $? == 0 )); then
-                    echo "Aborting."
-                    gotAns=1
-                    finished=1
-                    exitCode=1
-                else
-                    echo "Please answer y(es) or n(o)."
-                fi
-            fi
-        done
-    else
-        # We got the lock
-        finished=1
-        runTest
-    fi
-done
-
-# Close the lock file
-exec 9>&-
+### End Argument Parsing ###
 
 exit $exitCode
